name: Terraform destroy cicd

on:
  workflow_dispatch

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  destroy:
    name: terraform-destroy
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Setup terraform 
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5
      - name: Terraform init
        id: init
        run: terraform init
        working-directory: terraform-s3
      - name: Terraform destroy
        id: destroy
        run: terraform destroy -auto-approve
        working-directory: terraform-s3