name: terraform s3-static-webiste CICD

on: 
  push:
    branches:
      - master
    paths:
      - './backend'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform:
    name: AWS S3 Infrasturcure management
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Setup terraform 
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5
      - name: Terraform init
        id: init
        run: terraform init
        working-directory: ./terraform-s3
      - name: Terraform format
        id: fmt
        run: terraform fmt -check
        working-directory: terraform-s3
      - name: Terraform Validate
        id: validate
        run: terraform validate
        working-directory: terraform-s3
      - name: Terraform plan
        id: plan
        run: terraform plan
        working-directory: terraform-s3
      - name: Terraform apply
        id: apply
        run: terraform apply -auto-approve
        working-directory: terraform-s3